### ISSUE TITLE
Error in log - attempt to get length of a nil value

### ISSUE THREAD

**Issue by davidcreager** [toddaustin07/edge_upnp#1]
I 'think' scanning stops when it hits this

2021-09-17T15:22:49.206364203+00:00 DEBUG UPnP Package  [upnp] XML request URL=         http://192.168.1.163:1400/xml/device_description.xml
2021-09-17T15:22:49.355135662+00:00 WARN UPnP Package  Discovered device not recognized (name: 192.168.1.163 - Sonos One / model: Sonos One)
2021-09-17T15:22:49.359761537+00:00 WARN UPnP Package  Discovered device not recognized (name: 192.168.1.163 - Sonos One Media Server / model: Sonos One)
**2021-09-17T15:22:49.365418703+00:00 ERROR UPnP Package  discovery thread encountered error: [string "UPnP"]:82: attempt to get length of a nil value (field 'subdevices')**

**Comment by toddaustin07** [comment]
Ah looks like mal-formed device description XML from the device.  Could you plug the URL into a browser and post the XML here so I can see how it is formatted?

**Comment by davidcreager** [comment]
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:schemas-upnp-org:device:ZonePlayer:1</deviceType>
<friendlyName>192.168.1.163 - Sonos One</friendlyName>
<manufacturer>Sonos, Inc.</manufacturer>
<manufacturerURL>http://www.sonos.com</manufacturerURL>
<modelNumber>S13</modelNumber>
<modelDescription>Sonos One</modelDescription>
<modelName>Sonos One</modelName>
<modelURL>http://www.sonos.com/products/zoneplayers/S13</modelURL>
<softwareVersion>64.3-19080</softwareVersion>
<swGen>2</swGen>
<hardwareVersion>1.21.1.8-2.1</hardwareVersion>
<serialNum>78-28-CA-B1-71-BA:F</serialNum>
<MACAddress>78:28:CA:B1:71:BA</MACAddress>
<UDN>uuid:RINCON_7828CAB171BA01400</UDN>
<iconList>
<icon>
<id>0</id>
<mimetype>image/png</mimetype>
<width>48</width>
<height>48</height>
<depth>24</depth>
<url>/img/icon-S13.png</url>
</icon>
</iconList>
<minCompatibleVersion>63.0-00000</minCompatibleVersion>
<legacyCompatibleVersion>58.0-00000</legacyCompatibleVersion>
<apiVersion>1.24.1</apiVersion>
<minApiVersion>1.1.0</minApiVersion>
<displayVersion>13.2</displayVersion>
<extraVersion/>
<nsVersion>27</nsVersion>
<roomName>Dining Room</roomName>
<displayName>One</displayName>
<zoneType>15</zoneType>
<feature1>0x00000000</feature1>
<feature2>0x04c18332</feature2>
<feature3>0x0001500e</feature3>
<seriesid>A100</seriesid>
<variant>1</variant>
<internalSpeakerSize>5</internalSpeakerSize>
<bassExtension>75.000</bassExtension>
<satGainOffset>6.000</satGainOffset>
<memory>1024</memory>
<flash>1024</flash>
<ampOnTime>20</ampOnTime>
<retailMode>0</retailMode>
<SSLPort>1443</SSLPort>
<securehhSSLPort>1843</securehhSSLPort>
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:service:AlarmClock:1</serviceType>
<serviceId>urn:upnp-org:serviceId:AlarmClock</serviceId>
<controlURL>/AlarmClock/Control</controlURL>
<eventSubURL>/AlarmClock/Event</eventSubURL>
<SCPDURL>/xml/AlarmClock1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:MusicServices:1</serviceType>
<serviceId>urn:upnp-org:serviceId:MusicServices</serviceId>
<controlURL>/MusicServices/Control</controlURL>
<eventSubURL>/MusicServices/Event</eventSubURL>
<SCPDURL>/xml/MusicServices1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:DeviceProperties:1</serviceType>
<serviceId>urn:upnp-org:serviceId:DeviceProperties</serviceId>
<controlURL>/DeviceProperties/Control</controlURL>
<eventSubURL>/DeviceProperties/Event</eventSubURL>
<SCPDURL>/xml/DeviceProperties1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:SystemProperties:1</serviceType>
<serviceId>urn:upnp-org:serviceId:SystemProperties</serviceId>
<controlURL>/SystemProperties/Control</controlURL>
<eventSubURL>/SystemProperties/Event</eventSubURL>
<SCPDURL>/xml/SystemProperties1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:ZoneGroupTopology:1</serviceType>
<serviceId>urn:upnp-org:serviceId:ZoneGroupTopology</serviceId>
<controlURL>/ZoneGroupTopology/Control</controlURL>
<eventSubURL>/ZoneGroupTopology/Event</eventSubURL>
<SCPDURL>/xml/ZoneGroupTopology1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:GroupManagement:1</serviceType>
<serviceId>urn:upnp-org:serviceId:GroupManagement</serviceId>
<controlURL>/GroupManagement/Control</controlURL>
<eventSubURL>/GroupManagement/Event</eventSubURL>
<SCPDURL>/xml/GroupManagement1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-tencent-com:service:QPlay:1</serviceType>
<serviceId>urn:tencent-com:serviceId:QPlay</serviceId>
<controlURL>/QPlay/Control</controlURL>
<eventSubURL>/QPlay/Event</eventSubURL>
<SCPDURL>/xml/QPlay1.xml</SCPDURL>
</service>
</serviceList>
<deviceList>
<device>
<deviceType>urn:schemas-upnp-org:device:MediaServer:1</deviceType>
<friendlyName>192.168.1.163 - Sonos One Media Server</friendlyName>
<manufacturer>Sonos, Inc.</manufacturer>
<manufacturerURL>http://www.sonos.com</manufacturerURL>
<modelNumber>S13</modelNumber>
<modelDescription>Sonos One Media Server</modelDescription>
<modelName>Sonos One</modelName>
<modelURL>http://www.sonos.com/products/zoneplayers/S13</modelURL>
<UDN>uuid:RINCON_7828CAB171BA01400_MS</UDN>
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:service:ContentDirectory:1</serviceType>
<serviceId>urn:upnp-org:serviceId:ContentDirectory</serviceId>
<controlURL>/MediaServer/ContentDirectory/Control</controlURL>
<eventSubURL>/MediaServer/ContentDirectory/Event</eventSubURL>
<SCPDURL>/xml/ContentDirectory1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
<serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
<controlURL>/MediaServer/ConnectionManager/Control</controlURL>
<eventSubURL>/MediaServer/ConnectionManager/Event</eventSubURL>
<SCPDURL>/xml/ConnectionManager1.xml</SCPDURL>
</service>
</serviceList>
</device>
<device>
<deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
<friendlyName>Dining Room - Sonos One Media Renderer</friendlyName>
<manufacturer>Sonos, Inc.</manufacturer>
<manufacturerURL>http://www.sonos.com</manufacturerURL>
<modelNumber>S13</modelNumber>
<modelDescription>Sonos One Media Renderer</modelDescription>
<modelName>Sonos One</modelName>
<modelURL>http://www.sonos.com/products/zoneplayers/S13</modelURL>
<UDN>uuid:RINCON_7828CAB171BA01400_MR</UDN>
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>
<serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>
<controlURL>/MediaRenderer/RenderingControl/Control</controlURL>
<eventSubURL>/MediaRenderer/RenderingControl/Event</eventSubURL>
<SCPDURL>/xml/RenderingControl1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
<serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
<controlURL>/MediaRenderer/ConnectionManager/Control</controlURL>
<eventSubURL>/MediaRenderer/ConnectionManager/Event</eventSubURL>
<SCPDURL>/xml/ConnectionManager1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType>
<serviceId>urn:upnp-org:serviceId:AVTransport</serviceId>
<controlURL>/MediaRenderer/AVTransport/Control</controlURL>
<eventSubURL>/MediaRenderer/AVTransport/Event</eventSubURL>
<SCPDURL>/xml/AVTransport1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-sonos-com:service:Queue:1</serviceType>
<serviceId>urn:sonos-com:serviceId:Queue</serviceId>
<controlURL>/MediaRenderer/Queue/Control</controlURL>
<eventSubURL>/MediaRenderer/Queue/Event</eventSubURL>
<SCPDURL>/xml/Queue1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:GroupRenderingControl:1</serviceType>
<serviceId>urn:upnp-org:serviceId:GroupRenderingControl</serviceId>
<controlURL>/MediaRenderer/GroupRenderingControl/Control</controlURL>
<eventSubURL>/MediaRenderer/GroupRenderingControl/Event</eventSubURL>
<SCPDURL>/xml/GroupRenderingControl1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:VirtualLineIn:1</serviceType>
<serviceId>urn:upnp-org:serviceId:VirtualLineIn</serviceId>
<controlURL>/MediaRenderer/VirtualLineIn/Control</controlURL>
<eventSubURL>/MediaRenderer/VirtualLineIn/Event</eventSubURL>
<SCPDURL>/xml/VirtualLineIn1.xml</SCPDURL>
</service>
</serviceList>
<X_Rhapsody-Extension xmlns="http://www.real.com/rhapsody/xmlns/upnp-1-0">
<deviceID>urn:rhapsody-real-com:device-id-1-0:sonos_1:RINCON_7828CAB171BA01400</deviceID>
<deviceCapabilities>
<interactionPattern type="real-rhapsody-upnp-1-0"/>
</deviceCapabilities>
</X_Rhapsody-Extension>
<qq:X_QPlay_SoftwareCapability xmlns:qq="http://www.tencent.com">QPlay:2</qq:X_QPlay_SoftwareCapability>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<width>48</width>
<height>48</height>
<depth>24</depth>
<url>/img/icon-S13.png</url>
</icon>
</iconList>
</device>
</deviceList>
</device>
</root>`

**Comment by davidcreager** [comment]
Thanks for investigating.....let me know if you need anything else or a file of the xml  By the way my uPnP environment is a mess...so  this will be a good test!

**Comment by toddaustin07** [comment]
Hey David - After looking at this a bit closer, I have a couple questions regarding what the log is showing:

First - are you running the example driver from my channel, or did you load yourself from the cloned repository?

If the latter, did you make any modifications?  For example add/remove device models from the profiles table?

Do you have more of the log you could post?  I need to see a bit more what's going on prior and after to the lines you already posted.  I had initially assumed it was choking on something in the device description XML and that might still be the case, but I'm not positive.  

Would you be able to please post a pretty formatted version of the XML?  I'm having a hard time deciphering the structure of some of the Sonos-unique entries.  Do a view page source of the page as well, that will ensure you capture the first line which should be something like: 
```
<?xml version="1.0"?>
```
BTW, it looks like a real interesting device!  Multiple services and subdevices.

**Comment by davidcreager** [comment]
Sure.......Dont know if you use notepad++ but it has some cool xml tools...
[Bug.txt](https://github.com/toddaustin07/edge_upnp/files/7188875/Bug.txt)

**Comment by davidcreager** [comment]
ill try pasting it as well here
<root xmlns="urn:schemas-upnp-org:device-1-0">
	<specVersion>
		<major>1</major>
		<minor>0</minor>
	</specVersion>
	<device>
		<deviceType>urn:schemas-upnp-org:device:ZonePlayer:1</deviceType>
		<friendlyName>192.168.1.163 - Sonos One</friendlyName>
		<manufacturer>Sonos, Inc.</manufacturer>
		<manufacturerURL>http://www.sonos.com</manufacturerURL>
		<modelNumber>S13</modelNumber>
		<modelDescription>Sonos One</modelDescription>
		<modelName>Sonos One</modelName>
		<modelURL>http://www.sonos.com/products/zoneplayers/S13</modelURL>
		<softwareVersion>64.3-19080</softwareVersion>
		<swGen>2</swGen>
		<hardwareVersion>1.21.1.8-2.1</hardwareVersion>
		<serialNum>78-28-CA-B1-71-BA:F</serialNum>
		<MACAddress>78:28:CA:B1:71:BA</MACAddress>
		<UDN>uuid:RINCON_7828CAB171BA01400</UDN>
		<iconList>
			<icon>
				<id>0</id>
				<mimetype>image/png</mimetype>
				<width>48</width>
				<height>48</height>
				<depth>24</depth>
				<url>/img/icon-S13.png</url>
			</icon>
		</iconList>
		<minCompatibleVersion>63.0-00000</minCompatibleVersion>
		<legacyCompatibleVersion>58.0-00000</legacyCompatibleVersion>
		<apiVersion>1.24.1</apiVersion>
		<minApiVersion>1.1.0</minApiVersion>
		<displayVersion>13.2</displayVersion>
		<extraVersion/>
		<nsVersion>27</nsVersion>
		<roomName>Dining Room</roomName>
		<displayName>One</displayName>
		<zoneType>15</zoneType>
		<feature1>0x00000000</feature1>
		<feature2>0x04c18332</feature2>
		<feature3>0x0001500e</feature3>
		<seriesid>A100</seriesid>
		<variant>1</variant>
		<internalSpeakerSize>5</internalSpeakerSize>
		<bassExtension>75.000</bassExtension>
		<satGainOffset>6.000</satGainOffset>
		<memory>1024</memory>
		<flash>1024</flash>
		<ampOnTime>20</ampOnTime>
		<retailMode>0</retailMode>
		<SSLPort>1443</SSLPort>
		<securehhSSLPort>1843</securehhSSLPort>
		<serviceList>
			<service>
				<serviceType>urn:schemas-upnp-org:service:AlarmClock:1</serviceType>
				<serviceId>urn:upnp-org:serviceId:AlarmClock</serviceId>
				<controlURL>/AlarmClock/Control</controlURL>
				<eventSubURL>/AlarmClock/Event</eventSubURL>
				<SCPDURL>/xml/AlarmClock1.xml</SCPDURL>
			</service>
			<service>
				<serviceType>urn:schemas-upnp-org:service:MusicServices:1</serviceType>
				<serviceId>urn:upnp-org:serviceId:MusicServices</serviceId>
				<controlURL>/MusicServices/Control</controlURL>
				<eventSubURL>/MusicServices/Event</eventSubURL>
				<SCPDURL>/xml/MusicServices1.xml</SCPDURL>
			</service>
			<service>
				<serviceType>urn:schemas-upnp-org:service:DeviceProperties:1</serviceType>
				<serviceId>urn:upnp-org:serviceId:DeviceProperties</serviceId>
				<controlURL>/DeviceProperties/Control</controlURL>
				<eventSubURL>/DeviceProperties/Event</eventSubURL>
				<SCPDURL>/xml/DeviceProperties1.xml</SCPDURL>
			</service>
			<service>
				<serviceType>urn:schemas-upnp-org:service:SystemProperties:1</serviceType>
				<serviceId>urn:upnp-org:serviceId:SystemProperties</serviceId>
				<controlURL>/SystemProperties/Control</controlURL>
				<eventSubURL>/SystemProperties/Event</eventSubURL>
				<SCPDURL>/xml/SystemProperties1.xml</SCPDURL>
			</service>
			<service>
				<serviceType>urn:schemas-upnp-org:service:ZoneGroupTopology:1</serviceType>
				<serviceId>urn:upnp-org:serviceId:ZoneGroupTopology</serviceId>
				<controlURL>/ZoneGroupTopology/Control</controlURL>
				<eventSubURL>/ZoneGroupTopology/Event</eventSubURL>
				<SCPDURL>/xml/ZoneGroupTopology1.xml</SCPDURL>
			</service>
			<service>
				<serviceType>urn:schemas-upnp-org:service:GroupManagement:1</serviceType>
				<serviceId>urn:upnp-org:serviceId:GroupManagement</serviceId>
				<controlURL>/GroupManagement/Control</controlURL>
				<eventSubURL>/GroupManagement/Event</eventSubURL>
				<SCPDURL>/xml/GroupManagement1.xml</SCPDURL>
			</service>
			<service>
				<serviceType>urn:schemas-tencent-com:service:QPlay:1</serviceType>
				<serviceId>urn:tencent-com:serviceId:QPlay</serviceId>
				<controlURL>/QPlay/Control</controlURL>
				<eventSubURL>/QPlay/Event</eventSubURL>
				<SCPDURL>/xml/QPlay1.xml</SCPDURL>
			</service>
		</serviceList>
		<deviceList>
			<device>
				<deviceType>urn:schemas-upnp-org:device:MediaServer:1</deviceType>
				<friendlyName>192.168.1.163 - Sonos One Media Server</friendlyName>
				<manufacturer>Sonos, Inc.</manufacturer>
				<manufacturerURL>http://www.sonos.com</manufacturerURL>
				<modelNumber>S13</modelNumber>
				<modelDescription>Sonos One Media Server</modelDescription>
				<modelName>Sonos One</modelName>
				<modelURL>http://www.sonos.com/products/zoneplayers/S13</modelURL>
				<UDN>uuid:RINCON_7828CAB171BA01400_MS</UDN>
				<serviceList>
					<service>
						<serviceType>urn:schemas-upnp-org:service:ContentDirectory:1</serviceType>
						<serviceId>urn:upnp-org:serviceId:ContentDirectory</serviceId>
						<controlURL>/MediaServer/ContentDirectory/Control</controlURL>
						<eventSubURL>/MediaServer/ContentDirectory/Event</eventSubURL>
						<SCPDURL>/xml/ContentDirectory1.xml</SCPDURL>
					</service>
					<service>
						<serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
						<serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
						<controlURL>/MediaServer/ConnectionManager/Control</controlURL>
						<eventSubURL>/MediaServer/ConnectionManager/Event</eventSubURL>
						<SCPDURL>/xml/ConnectionManager1.xml</SCPDURL>
					</service>
				</serviceList>
			</device>
			<device>
				<deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
				<friendlyName>Dining Room - Sonos One Media Renderer</friendlyName>
				<manufacturer>Sonos, Inc.</manufacturer>
				<manufacturerURL>http://www.sonos.com</manufacturerURL>
				<modelNumber>S13</modelNumber>
				<modelDescription>Sonos One Media Renderer</modelDescription>
				<modelName>Sonos One</modelName>
				<modelURL>http://www.sonos.com/products/zoneplayers/S13</modelURL>
				<UDN>uuid:RINCON_7828CAB171BA01400_MR</UDN>
				<serviceList>
					<service>
						<serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>
						<serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>
						<controlURL>/MediaRenderer/RenderingControl/Control</controlURL>
						<eventSubURL>/MediaRenderer/RenderingControl/Event</eventSubURL>
						<SCPDURL>/xml/RenderingControl1.xml</SCPDURL>
					</service>
					<service>
						<serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
						<serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
						<controlURL>/MediaRenderer/ConnectionManager/Control</controlURL>
						<eventSubURL>/MediaRenderer/ConnectionManager/Event</eventSubURL>
						<SCPDURL>/xml/ConnectionManager1.xml</SCPDURL>
					</service>
					<service>
						<serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType>
						<serviceId>urn:upnp-org:serviceId:AVTransport</serviceId>
						<controlURL>/MediaRenderer/AVTransport/Control</controlURL>
						<eventSubURL>/MediaRenderer/AVTransport/Event</eventSubURL>
						<SCPDURL>/xml/AVTransport1.xml</SCPDURL>
					</service>
					<service>
						<serviceType>urn:schemas-sonos-com:service:Queue:1</serviceType>
						<serviceId>urn:sonos-com:serviceId:Queue</serviceId>
						<controlURL>/MediaRenderer/Queue/Control</controlURL>
						<eventSubURL>/MediaRenderer/Queue/Event</eventSubURL>
						<SCPDURL>/xml/Queue1.xml</SCPDURL>
					</service>
					<service>
						<serviceType>urn:schemas-upnp-org:service:GroupRenderingControl:1</serviceType>
						<serviceId>urn:upnp-org:serviceId:GroupRenderingControl</serviceId>
						<controlURL>/MediaRenderer/GroupRenderingControl/Control</controlURL>
						<eventSubURL>/MediaRenderer/GroupRenderingControl/Event</eventSubURL>
						<SCPDURL>/xml/GroupRenderingControl1.xml</SCPDURL>
					</service>
					<service>
						<serviceType>urn:schemas-upnp-org:service:VirtualLineIn:1</serviceType>
						<serviceId>urn:upnp-org:serviceId:VirtualLineIn</serviceId>
						<controlURL>/MediaRenderer/VirtualLineIn/Control</controlURL>
						<eventSubURL>/MediaRenderer/VirtualLineIn/Event</eventSubURL>
						<SCPDURL>/xml/VirtualLineIn1.xml</SCPDURL>
					</service>
				</serviceList>
				<X_Rhapsody-Extension xmlns="http://www.real.com/rhapsody/xmlns/upnp-1-0">
					<deviceID>urn:rhapsody-real-com:device-id-1-0:sonos_1:RINCON_7828CAB171BA01400</deviceID>
					<deviceCapabilities>
						<interactionPattern type="real-rhapsody-upnp-1-0"/>
					</deviceCapabilities>
				</X_Rhapsody-Extension>
				<qq:X_QPlay_SoftwareCapability xmlns:qq="http://www.tencent.com">QPlay:2</qq:X_QPlay_SoftwareCapability>
				<iconList>
					<icon>
						<mimetype>image/png</mimetype>
						<width>48</width>
						<height>48</height>
						<depth>24</depth>
						<url>/img/icon-S13.png</url>
					</icon>
				</iconList>
			</device>
		</deviceList>
	</device>
</root>

**Comment by toddaustin07** [comment]
The file worked; thank you!

**Comment by davidcreager** [comment]
Oh good   By the way....I just noticed I got the same error on another device....Its late here tomorrow so I will investigate further tomorrow

**Comment by davidcreager** [comment]
but  just before I crash for the night  here is another
[bug2.txt](https://github.com/toddaustin07/edge_upnp/files/7188884/bug2.txt)

I'think' denon device caused the bug

**Comment by toddaustin07** [comment]
I found and corrected the issue.  There was nothing wrong with the device description XML.  It was a bug in my code that parses it.   For some un-fortuitous reason, the particular line of code was never exercised with any of my devices.  

I ran both the Sonos and Denon device xml through my updated code and they should be working ok now.  

FYI, you'll get a warning on the Denon device that service list is missing, because there is none included for the root device.  There are service lists for the subdevices, though, so you'll have to modify the example driver to pick one of the subdevices for subscribing or sending commands.  (By default it just tries to use the first service of the root device.)

The Sonos XML also allowed me to improve the pretty print function found in the UPNP/printdesc.lua module.

I've updated github, so please pull the latest files, retest, and confirm that this has fixed the problems.

THANK YOU for your help and patience!

**Comment by davidcreager** [comment]
> Hey David - After looking at this a bit closer, I have a couple questions regarding what the log is showing:
> 
> First - are you running the example driver from my channel, or did you load yourself from the cloned repository?
> 
> If the latter, did you make any modifications? For example add/remove device models from the profiles table?
> 
> Do you have more of the log you could post? I need to see a bit more what's going on prior and after to the lines you already posted. I had initially assumed it was choking on something in the device description XML and that might still be the case, but I'm not positive.
> 
> Would you be able to please post a pretty formatted version of the XML? I'm having a hard time deciphering the structure of some of the Sonos-unique entries. Do a view page source of the page as well, that will ensure you capture the first line which should be something like:
> 
> ```
> <?xml version="1.0"?>
> ```
> 
> BTW, it looks like a real interesting device! Multiple services and subdevices.

ARgh....I didnt see this....sorry.....it was late last night.....I cloned repository and loaded from my channel.   I did not modify.   Sorry I didnt do the view source.   If you still want then just let me know.   I'm just about to test your latest release.  will close if it works

**Comment by davidcreager** [comment]
Perfect  issue fixed!  Thanks
