### ISSUE TITLE
Question rather than Issue - I tried the logcat command and device discovery after a valid scan and no output

### ISSUE THREAD

**Issue by davidcreager** [toddaustin07/edge_upnp#2]
After I applied your fix, the logcat completed.   I tried to run again  and received nothing?   Any ideas what i'm doing wrong?

**Comment by toddaustin07** [comment]
Not sure what you mean by your first sentence.  What do you mean the logcat completed?  You should pretty much see a non-stop stream of messages; it really should never end.  

Do you have the same driver ID?  Had you just updated the driver (with same driver ID) and left your existing devices?   Or did you try deleting all your UPnP devices first so you would start from scratch.  There are so many scenarios, it's hard for me to troubleshoot.

**Comment by davidcreager** [comment]
Ok...It maybe that this is too big a subject, I will close the issue after this attempt.

The logcat indicated the scan was complete and I ctrl c'd it.
I have never seen devices discovered (in the app) and have not added any from any edge driver (other than Hello World)
I uninstalled the first driver and installed the updated code.

Sorry to be an idiot.

Just to be clear  here is what I did

Downloaded your code (git pull)
Uninstalled the old driver
installed the new driver
ran logcat and an add device  scan on the phone app
received the output showing your fix had worked.
control c'd the logcat and ended the scan

All seemed good

about an hour later
ran the logcat app and an add device scan on my phone
No output!

I repeated a couple of times and posted here

**Comment by toddaustin07** [comment]
That should not be happening.  I've seen a similar issue posted on the community.  Take a look at this one and see if it is similar to what you are experiencing:  https://community.smartthings.com/t/smartthings-edge-developer-beta-known-issues-and-bug-tracking/230389/19?u=taustin



Uninstalled the old driver - _were there any devices previously found?  you must have deleted them all first?_
installed the new driver 
ran logcat and an add device scan on the phone app
received the output showing your fix had worked. - _did you get devices created?_
control c'd the logcat and ended the scan - _if you can, just leave this running.  Then next time you try to replicate this you may have more useful debugging info_

All seemed good

about an hour later
ran the logcat app and an add device scan on my phone - _before you even ran the new device scan, were you seeing log messages?  You should them very regularly if you have much UPnp activity on your LAN.  Were you expecting any new devices to be discovered at this point?_
No output! - _at this point did your previously created devices appear to be still online and working? (Try pressing the button on the device dashboard)_

**Comment by davidcreager** [comment]
Mmmmh very odd!

I can't see any devices on the phone app (ie with no room assigned)
I don't think the phone app found any devices  can't actually be sure as I was excited that the logcat was finding devices and the bug was fixed.

I don't think there were any devices found on the old version, I certainly did not delete them and it allowed me to uninstall.

' You should them very regularly if you have much UPnp activity on your LAN. Were you expecting any new devices to be discovered at this point?'   Aha maybe here is my mis-understanding. What do you mean by 'new'     If I don't create a device (on my phone I guess)  I was expecting all the devices  to carry on being seen and output to logcat when I do a new phone scan..   Have I got this wrong?  Has the  hub marked them as been seen in some way?

I'll try again tomorrow....no stress......I'm playing with something else at the moment -:)

**Comment by toddaustin07** [comment]
You never said if you were using the example driver from the github repository or the one available via my shared driver channel, but I assume it is the former.  If that is the case, don't forget that before you get any devices created, you have to edit the init.lua code and plug in the model numbers of the devices you want it to recognize.  That's all explained in the documentation.  

The driver you can install from my channel does not require any editing and will add ANY device it finds.  This is because the channel delivery approach is for end-users who don't want to get involved with code.  The github package is more oriented to folks like you that want to dig into the code, so the example driver was left to you to modify and tweek for your particular devices.

**Comment by davidcreager** [comment]
Ok....I must have been tired or dreaming or just an idiot.....this is nonsense, I uninstalled and installed the driver again and it all works fine....discovers 238 devices every time I run  a scan..  Sorry for causing confusion
