### ISSUE TITLE
`should_continue` is a function - API 40.x

### ISSUE THREAD

**Issue by w35l3y** [toddaustin07/edge_upnp#3]
First, thanks for all your great work. I am learning a lot from your codes.

https://github.com/toddaustin07/edge_upnp/blob/792dc04be1d856aa82b1e1cee8a9a3debf02094a/upnpdrivertemplate.lua#L398

According to API 40.x below, `should_continue` is a function.
So the first condition above is **always** true.
It should be a quick fix just by adding `()` to call that function without any parameter.
```
local should_continue = function() return self.discovery_state.is_running or false end
self.discovery_state.is_running = true
self.discovery_state.thread:queue_event(self.discovery, self, opts, should_continue)
```

**Comment by toddaustin07** [comment]
Thank you, you are correct!  I never use should_continue myself, so never caught this error!  For my LAN drivers I usually use my own retry counter :-)

I will make this change in the file.
